# Generated by Django 4.2 on 2026-02-18 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_received', models.DateField(auto_now_add=True)),
                ('payment_terms', models.CharField(blank=True, max_length=200)),
                ('delivery_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting_vendor', 'Waiting Vendor Response'), ('partially_quoted', 'Partially Quoted'), ('fully_quoted', 'Fully Quoted'), ('won', 'Won'), ('lost', 'Lost'), ('closed', 'Closed')], default='open', max_length=30)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('email', 'Email'), ('bulk_paste', 'Bulk Paste'), ('ai_parsed', 'AI Parsed')], default='manual', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('external_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rfqs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rfqs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='companies.company')),
            ],
            options={
                'verbose_name': 'RFQ',
                'verbose_name_plural': 'RFQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('part_number_raw', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('condition_required', models.CharField(blank=True, max_length=100, verbose_name='CD')),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('line_status', models.CharField(choices=[('open', 'Open'), ('quoted', 'Quoted'), ('no_offer', 'No Offer'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parts.part')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rfq.rfq')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='RFQAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='rfq.rfq')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
