# Generated by Django 4.2 on 2026-02-19 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rfq', '0001_initial'),
        ('email_integration', '0002_remove_emaillog_message_id_emailaccount_created_by_and_more'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_rfqs', to='rfq.rfq')),
                ('outbound_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_rfq_sent', to='email_integration.emaillog')),
                ('reply_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_rfq_reply', to='email_integration.emaillog')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_rfqs', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorRFQLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('line_number', models.IntegerField(default=1)),
                ('inquiry_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_lines', to='rfq.rfqline')),
                ('vendor_rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vendor_rfq.vendorrfq')),
            ],
            options={
                'ordering': ['line_number'],
                'unique_together': {('vendor_rfq', 'inquiry_line')},
            },
        ),
        migrations.CreateModel(
            name='VendorQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity_available', models.IntegerField()),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('certification', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manually Entered'), ('email', 'Parsed from Email')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor_rfq_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='vendor_rfq.vendorrfqline')),
            ],
            options={
                'ordering': ['unit_price'],
            },
        ),
        migrations.CreateModel(
            name='VendorSuggestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200)),
                ('reason', models.CharField(choices=[('quote_history', 'Previously Quoted This Part'), ('inventory', 'Stocks This Part in Inventory'), ('category', 'Matched Part Category'), ('fallback', 'No Match — Showing All Vendors')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfq.rfq')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'unique_together': {('inquiry', 'vendor', 'part_number')},
            },
        ),
    ]
