# Generated by Django 4.2 on 2026-02-19 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_integration', '0002_remove_emaillog_message_id_emailaccount_created_by_and_more'),
        ('vendor_rfq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedVendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_parsed', models.JSONField(default=dict)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('email_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='email_integration.emaillog')),
                ('vendor_rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_quotes', to='vendor_rfq.vendorrfq')),
            ],
        ),
    ]
