# Generated by Django 4.2.28 on 2026-02-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_rfq', '0002_parsedvendorquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrfqline',
            name='is_winner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
