# Generated by Django 4.2 on 2026-02-18 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending QC'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('quality_check_passed', models.BooleanField(default=False)),
                ('quality_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='purchase_orders.purchaseorder')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GRNLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=4, max_digits=15)),
                ('quality_ok', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='receiving.goodsreceiptnote')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase_orders.purchaseorderline')),
            ],
        ),
    ]
