# Generated by Django 4.2 on 2026-02-18 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('manufacturer_code', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('uom', models.CharField(default='EA', max_length=50, verbose_name='Unit of Measure')),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('as_is', 'As-Is')], max_length=20)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('alternate_pn', models.CharField(blank=True, max_length=100, verbose_name='Alternate Part Number')),
                ('superseded_pn', models.CharField(blank=True, max_length=100, verbose_name='Superseded Part Number')),
                ('internal_notes', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
