# Generated by Django 4.2 on 2026-02-18 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_orders', '0001_initial'),
        ('companies', '0001_initial'),
        ('sales_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('own_stock', 'Own Stock'), ('vendor_offer', 'Vendor Offer'), ('customer_offer', 'Customer Offer'), ('push_list', 'Push List')], default='own_stock', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('quantity_available', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('as_is', 'As-Is')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('lead_time', models.CharField(blank=True, max_length=100)),
                ('reference_tag', models.CharField(blank=True, max_length=200)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linked_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_orders.purchaseorder')),
                ('linked_so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_orders.salesorder')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='parts.part')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_offers', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
