# Generated by Django 4.2 on 2026-02-18 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rfq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=10)),
                ('validity_days', models.IntegerField(default=30)),
                ('payment_terms', models.CharField(blank=True, max_length=200)),
                ('delivery_terms', models.CharField(blank=True, max_length=200)),
                ('header_notes', models.TextField(blank=True)),
                ('footer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('template', models.CharField(default='default', max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='companies.company')),
                ('rfq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='rfq.rfq')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('part_number_raw', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('cost_source', models.CharField(choices=[('inventory', 'From Inventory'), ('vendor_offer', 'Vendor Offer'), ('manual', 'Manual Entry')], default='manual', max_length=20)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('lead_time', models.CharField(blank=True, max_length=100)),
                ('reference_tag', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parts.part')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quote')),
                ('rfq_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rfq.rfqline')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
    ]
