# Generated by Django 4.2 on 2026-02-18 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting_po', 'Waiting PO'), ('partially_received', 'Partially Received'), ('ready_to_ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=30)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=10)),
                ('payment_terms', models.CharField(blank=True, max_length=200)),
                ('delivery_terms', models.CharField(blank=True, max_length=200)),
                ('shipping_address', models.TextField(blank=True)),
                ('customer_po_number', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=200)),
                ('payment_received', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='companies.company')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='quotes.quote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('part_number_raw', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity_ordered', models.DecimalField(decimal_places=4, max_digits=15)),
                ('quantity_shipped', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('allocated_charges', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('lead_time', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('allocated', 'Allocated'), ('partially_shipped', 'Partially Shipped'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='open', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parts.part')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales_orders.salesorder')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
    ]
