# Generated by Django 4.2 on 2026-02-18 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='message_id',
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='last_history_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='oauth2_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='oauth2_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='oauth2_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='gmail_message_id',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='relevance_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='relevance_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedemaildata',
            name='ai_model_used',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parsedemaildata',
            name='confirmed_lines',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='parsedemaildata',
            name='parse_duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='imap_host',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('irrelevant', 'Irrelevant'), ('confirmed', 'Confirmed'), ('processed', 'Processed'), ('failed', 'Failed'), ('sent', 'Sent')], default='received', max_length=20),
        ),
    ]
