# Generated by Django 4.2 on 2026-02-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_integration', '0002_remove_emaillog_message_id_emailaccount_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='gmail_message_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
