# Generated by Django 4.2 on 2026-02-23 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0001_initial'),
        ('email_integration', '0003_alter_emaillog_gmail_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('new_inquiry', 'New Inquiry'), ('rfq_reply', 'RFQ Reply'), ('vendor_reply', 'Vendor Reply'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='gmail_thread_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='in_reply_to',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='linked_inquiry',
            field=models.ForeignKey(blank=True, help_text='For reply emails: the original inquiry/outbound email this is responding to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='email_integration.emaillog'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='message_id_header',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='references_header',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parsedemaildata',
            name='manually_entered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='from_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='gmail_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='parsed_rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='rfq.rfq'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('parse_failed', 'Parse Failed'), ('irrelevant', 'Irrelevant'), ('confirmed', 'Confirmed'), ('processed', 'Processed'), ('failed', 'Failed'), ('sent', 'Sent')], default='received', max_length=20),
        ),
    ]
